### PR TITLE
Qol 892 publish tasks

### PR DESCRIPTION
**Pull request by AsifAmin**
@shraka 
I have made some changes. 

1.) Making testing mandatory to run build and release process. I think any developer can comment in few tasks in gulpfile to get a temporary build to test something in hurry.

2.) Added publish tasks (currently using test npm account till we have an official npm account)

3.) Checked some of the linting issues

### CODE REVIEW

**Comment by shraka** [comment]
1.) The build process needs to have a non-fail on error build option without having to comment and un-comment build process code. Requiring devs to comment / un-comment code in the build process when not working on the build process carries too high a risk for error.

**Comment by AsifAmin** [comment]
I think if we make a process where developers can build without testing can create much greater risks. Anyone can make an excuse that they have built using soft build.

I like to test because it helps in debugging. I dont think we should make a process of lazy builds.

I have never seen any soft build(without testing) in any project before in any qld gov projects. You know of any project where we did this before?

**Comment by shraka** [comment]
Given the tests are still run on build, and the release process will halt if it encounters an error, and that this is an internal project with our own quality controls, I don't see this as a big risk.

**Comment by shraka** [comment]
Had a chat to Eru about this and mitigation. My risk assessment:

1) With tests that don't halt build:
- Developers will be lazy and merge un-releasable code. Mitigation: Tighter QM controls

2) With tests that halt build:
- Developers will comment out build process and cause conflicts. Mitigation: Standard that we don't change the testing process to make code pass.

The mitigation for option 2 (your option) is probably easier to implement, if you're happy to stick to that.

**Comment by AsifAmin** [comment]
By comment out I mean on their own risk if anyone want to do that. **Officially**, it is good to have only one build with complete testing. In this way we can assure that by default we are producing the right code.

**Pull request merged**
