### PR TITLE
Feature/qol 1101 maps js transfer

### PR DESCRIPTION
**Pull request by gvanimurthy**
Transferred dependency pagination component.

### CODE REVIEW

**Comment by AsifAmin** [comment]
@gvanimurthy 
How we can use this with the components like tables, maps?

Pagination will always be on a page with some other components like tables , maps. I think we need  some kind of API to connect pagination with the other components. ?

**Comment by gvanimurthy** [comment]
@AsifAmin 
As discussed, integration of pagination component will be demonstrated in components which is using pagination. This pull request demonstrates only pagination functionality as a standalone component with scope to improve later.

**Comment by AsifAmin** [comment]
@gvanimurthy @shraka 
I think may be going forward we can strip build process for the components that are only of use when using  with other components like data , pagination etc ?

They can only contain the file and the test specification like **data.js and data.spec.js**

**Comment by gvanimurthy** [comment]
@AsifAmin @shraka 
As discussed, data and pagination modules are under the scope of future improvement and hence been decided to have build system as well.

**Comment by shraka** [comment]
@AsifAmin @gvanimurthy  I agree with Vani. These are publicly facing services and need to be tested and released independently.

**Pull request merged**
